### ISSUE TITLE
Fall Damage trigger

### ISSUE THREAD

**Issue by KingMickeyMe** [AlonsoAliaga/BetterRevive#2]
**Describe the bug**
When launching yourself upwards while standing still, the bleeding prompt will start upon hitting the ground, it will lower your health to half a heart and then kill you unless revived.

This is a normal behavior, but it also happens to people with fall damage negated. The people will go on fine, continuing to walk around, but due to the prompt, they will die after the cooldown.

**To Reproduce**
1. Launch yourself straight upwards with fall damage protection
2. Bleeding out prompt will appear and will lower your health to half a heart, and you are free to walk around as normal until the timer runs out and it kills you.

**Expected behavior**
If fall damage is negated, the prompt should not appear when falling from a terminal height.

**Screenshots**

**Important (please complete the following information):**
 - Java version: [e.g. 8, 9, 10, 11, 12] Java 8 Update 261
 - Plugin version: [e.g. ALPHA-0.1] 0.1-BETA
 - Server version [Use /icanhasbukkit in console] This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Additional context**

**Comment by KingMickeyMe** [comment]
NOTE: This bug seems to only happen when shooting straight upwards, if launching at an angle or going in a direction, people with fall damage protection seem to be fine.

**Comment by AlonsoAliaga** [comment]
Issue was fixed on 0.2-BETA release.
