### ISSUE TITLE
/giveup can't dead

### ISSUE THREAD

**Issue by Iverins** [AlonsoAliaga/BetterRevive#3]
**Describe the bug**
Input /giveup automatic resurrection

**To Reproduce**
1. When you are near death
2. Input /giveup
3. Then you can be resurrected with only one blood
4. No error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/30949525/99148322-0982a580-26c2-11eb-8628-c9fc0ca093ba.png)
![image](https://user-images.githubusercontent.com/30949525/99148330-12737700-26c2-11eb-9244-f7addbe03639.png)

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: 0.3-BETA
 - Server version [Use /icanhasbukkit in console]  git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT

**Additional context**
.

**Comment by AlonsoAliaga** [comment]
Make sure you are not in a worldguard region or any other plugin preventing you from taking damage

**Comment by Iverins** [comment]
> Make sure you are not in a worldguard region or any other plugin preventing you from taking damage
Sure.

**Comment by Iverins** [comment]
![image](https://user-images.githubusercontent.com/30949525/99148574-7cd8e700-26c3-11eb-95f2-6570a9dc95fc.png)
There are all plugins on my server.And I’m not in Residence’s territory.

**Comment by AlonsoAliaga** [comment]
Ok. I'll take a look in the code in some hours

**Comment by Iverins** [comment]
> Ok. I'll take a look in the code in some hours

Thanks for your hard work

**Comment by AlonsoAliaga** [comment]
Hello! Can you join my discord server https://discord.gg/DEDaQhs so you can test a dev build?

**Comment by AlonsoAliaga** [comment]
Hello you still there? I'm making some changes to the plugin. I'm pushing an update probably tomorrow after some tests.
Join my discord server when you can

**Comment by AlonsoAliaga** [comment]
Issue should be fixed in 0.4-BETA.
Join our server if you have any issue 😉
