### ISSUE TITLE
Minecart

### ISSUE THREAD

**Issue by WongIong** [AlonsoAliaga/BetterRevive#5]
**Describe the bug**
Player can get on a minecart or a boat to get away from the location.

**To Reproduce**

**Expected behavior**
They should instantly get off the minecart and boat.

**Screenshots**

**Important (please complete the following information):**
 - Java version: 16
 - Plugin version: 0.9.1-BETA
 - Server version paper 1.16.5-794

**Additional context**

**Comment by AlonsoAliaga** [comment]
I'll take a look when i have some free time from college. Thanks for the
report

**Comment by AlonsoAliaga** [comment]
Hello, do you have "Options.Block.Interact-at-entity" set to true?
Can you join our discord server on https://alonsoaliaga.com/discord to be able to reply a bit faster for this problem?
Let me know

**Comment by AlonsoAliaga** [comment]
Solved in 0.9.2-BETA (Pending to update)
