### ISSUE TITLE
in some cases player can escape from the barrier when dying

### ISSUE THREAD

**Issue by WongIong** [AlonsoAliaga/BetterRevive#6]
**Describe the bug**
if player has speed boost then they can keep running and won't be forced to lay down.

**To Reproduce**
1. get speed boost (in this case is from other plugin that can change movement speed)
2. go into dying mode
3. keep running

**Expected behavior**
maybe just extend the barrier's range?

**Screenshots**

**Important (please complete the following information):**
 - Java version: 16
 - Plugin version: 0.9.1
 - Server version paper 1.16.5

**Additional context**
also i can't give players slowness effect, its in the config.yml but no slowness are given to player.
other effect seems working fine

**Comment by AlonsoAliaga** [comment]
Hello, issue is that we place blocks above the player to be able to have crawling/swimming animation, i recommend testing with SLOW with amplifier of 127 so player cannot move, or less tto reduce player speed.

"maybe just extend the barrier's range?"
This isn't too good tbh, i'll probably give it a try soon but that means more blocks will be "replaced" for the player view and I rather not doing that. Give it a try to the SLOW thing i mentioned above

**Comment by AlonsoAliaga** [comment]
Solved in 0.9.2-BETA (Pending to update)
